### Genome version considerations

# genome_name should match bams
genome_path: "/gsc/resources/Homo_sapiens_genomes/hg38_no_alt_TCGA_HTMCP_HPVs/genome/fasta/hg38_no_alt_TCGA_HTMCP_HPVs.fa"
transcriptome_path: "/gsc/resources/Homo_sapiens_genomes/hg38_no_alt_TCGA_HTMCP_HPVs/transcriptome/star-2.5.2b/hg38_no_alt_TCGA_HTMCP_HPVs_ensembl100_gsc_v1/"

